
###############################################################################
#
# Inclusive Makefile for the onlplib module.
#
# Autogenerated 2014-07-02 07:52:07.537340
#
###############################################################################
onlplib_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(onlplib_BASEDIR)/module/make.mk
include $(onlplib_BASEDIR)/module/auto/make.mk
include $(onlplib_BASEDIR)/module/src/make.mk
include $(onlplib_BASEDIR)/utest/_make.mk

