
###############################################################################
#
# Inclusive Makefile for the onlplib module.
#
# Autogenerated 2015-04-20 15:00:54.843643
#
###############################################################################
onlplib_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(onlplib_BASEDIR)/module/make.mk
include $(onlplib_BASEDIR)/module/auto/make.mk
include $(onlplib_BASEDIR)/module/src/make.mk
include $(onlplib_BASEDIR)/utest/_make.mk

