################################################################
# <bsn.cl fy=2014 v=onl>
# </bsn.cl>
################################################################
include ../init.mk

-include Manifest.mk

include $(BUILDER)/moduledir.mk

#
# Available targets
#
moduledir_show_targets::
	@echo "    autogen                     Make autogen in all modules."

autogen:




