
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2014-03-20 12:30:52.258033
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
onlp_BASEDIR := $(BASEDIR)onlp
onlpie_BASEDIR := $(BASEDIR)onlpie


ALL_MODULES := $(ALL_MODULES) onlp onlpie
