
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2015-08-05 09:18:26.185518
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
onlp_BASEDIR := $(BASEDIR)onlp
onlp_platform_defaults_BASEDIR := $(BASEDIR)onlp_platform_defaults
onlp_snmp_BASEDIR := $(BASEDIR)onlp_snmp
onlpie_BASEDIR := $(BASEDIR)onlpie
onlplib_BASEDIR := $(BASEDIR)onlplib
sff_BASEDIR := $(BASEDIR)sff


ALL_MODULES := $(ALL_MODULES) onlp onlp_platform_defaults onlp_snmp onlpie onlplib sff
