
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2014-04-01 12:31:45.610814
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
onlp_BASEDIR := $(BASEDIR)onlp/onlp
onlp_platform_defaults_BASEDIR := $(BASEDIR)onlp/onlp_platform_defaults
onlpie_BASEDIR := $(BASEDIR)onlpie
onlplib_BASEDIR := $(BASEDIR)onlp/onlplib


ALL_MODULES := $(ALL_MODULES) onlp onlp_platform_defaults onlpie onlplib
