###############################################################################
#
# Local source generation targets.
#
###############################################################################
include ../../../../init.mk

ucli:
	$(SUBMODULE_BIGCODE)/tools/uclihandlers.py onlp_ucli.c

