/**************************************************************************//**
 *
 *
 *
 *****************************************************************************/
#include <onlp/onlp_config.h>

#if ONLP_CONFIG_INCLUDE_UCLI == 1

#include <uCli/ucli.h>
#include <uCli/ucli_argparse.h>
#include <uCli/ucli_handler_macros.h>

static ucli_status_t
onlp_ucli_ucli__config__(ucli_context_t* uc)
{
    UCLI_HANDLER_MACRO_MODULE_CONFIG(onlp)
}

/* <auto.ucli.handlers.start> */
/******************************************************************************
 *
 * These handler table(s) were autogenerated from the symbols in this
 * source file.
 *
 *****************************************************************************/
static ucli_command_handler_f onlp_ucli_ucli_handlers__[] = 
{
    onlp_ucli_ucli__config__,
    NULL
};
/******************************************************************************/
/* <auto.ucli.handlers.end> */

static ucli_module_t
onlp_ucli_module__ =
    {
        "onlp_ucli",
        NULL,
        onlp_ucli_ucli_handlers__,
        NULL,
        NULL,
    };

ucli_node_t*
onlp_ucli_node_create(void)
{
    ucli_node_t* n;
    ucli_module_init(&onlp_ucli_module__);
    n = ucli_node_create("onlp", NULL, &onlp_ucli_module__);
    ucli_node_subnode_add(n, ucli_module_log_node_create("onlp"));
    return n;
}

#else
void*
onlp_ucli_node_create(void)
{
    return NULL;
}
#endif

