###############################################################################
#
#
#
###############################################################################
include ../../../init.mk
MODULE := onlp_platform_defaults
AUTOMODULE := onlp_platform_defaults
include $(BUILDER)/definemodule.mk
