
###############################################################################
#
# Inclusive Makefile for the onlp_platform_defaults module.
#
# Autogenerated 2016-05-17 13:22:27.275132
#
###############################################################################
onlp_platform_defaults_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(onlp_platform_defaults_BASEDIR)module/make.mk
include $(onlp_platform_defaults_BASEDIR)module/auto/make.mk
include $(onlp_platform_defaults_BASEDIR)module/src/make.mk
include $(onlp_platform_defaults_BASEDIR)utest/_make.mk

